### ISSUE TITLE
Google sign-in is not working

### ISSUE THREAD

**Issue by abd-khrubi** [fouadhal/project#1]
Signing in using Google auth gives this exception:
```
2020-10-04 19:53:20.333 30413-30413/com.example.project D/LoginAuthentication: Google sign in failed
    com.google.android.gms.common.api.ApiException: 10: 
        at com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(com.google.android.gms:play-services-base@@17.3.0:4)
        at com.google.android.gms.auth.api.signin.GoogleSignIn.getSignedInAccountFromIntent(com.google.android.gms:play-services-auth@@18.1.0:9)
        at com.example.project.LoginActivity.onActivityResult(LoginActivity.java:211)
        at android.app.Activity.dispatchActivityResult(Activity.java:8300)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5353)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5401)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

**Comment by abd-khrubi** [comment]
@fouadhal

**Comment by fouadhal** [comment]
@abd-khrubi 
You have to add your SHA certificate in Firebase project settings;
- In Android Studio on the right side there should be a tab named "Grade"
- In it, go to Project -> app -> Tasks -> android  and run signingReport
- There should be a result 'Variant: debugUnitTest', copy the SHA1 from there
- Go to Project Settings in Firebase, in General scroll down and add your SHA1 as a Fingerprint
( https://developers.google.com/android/guides/client-auth )

As I understand, once the application is released to Playstore we will only need the release key.

**Comment by abd-khrubi** [comment]
Thanks, but this won't be an issue on release, right?

**Comment by fouadhal** [comment]
Yea it shouldn't be. I've read that once it is realeased only 1 key is needed.

**Comment by abd-khrubi** [comment]
Great
